feat: jsonl output and quiet stdout
doitintl/kube-no-trouble pull request #121
Opened 2021-03-31 15:34 UTC by leepa

To support better automated usage.

New options:

 * -q will quiet the stderr log output
 * -o jsonl will, instead out outputting a list, output one infraction
   per line. This is good if you're loading the data into data
   warehouses or other reporting tools.

2021-03-31 15:45 UTC, david-doit-intl commented on pkg/printer/json_test.go
> +		t.Errorf("OnePerLine should default to false")
OnePerLine should be set to true

2021-03-31 15:46 UTC, david-doit-intl commented on pkg/printer/json_test.go
> +	x, _ := NewJSONPrinter(&JSONOpts{OnePerLine: false})
x -> jsonPrinter

2021-03-31 15:46 UTC, david-doit-intl commented on pkg/printer/json.go
> +			b, err := json.Marshal(entry)
b-> bytes?

2021-03-31 15:49 UTC, leepa commented on pkg/printer/json_test.go
> +		t.Errorf("OnePerLine should default to false")
Good catch

2021-03-31 15:50 UTC, david-doit-intl requested changes
LGTM aside from some little changes @stepanstipl WDYT

2021-03-31 15:59 UTC, stepanstipl commented
Thanks @leepa for contributing! Before looking at the implementation details, I would suggest splitting these into 2 PRs, as these seem to be unrelated changes, so as not to mix the conversation. But TL;DR: for both of those I would like to discuss/see an example of use cases, more specifically:

- `-q` - is there any benefit/use case when same can't be achieved by ignoring stderr?
- `-o jsonl` - kind of same, I'm a bit concerned about introducing a somewhat arbitrary output format, but I would like to understand the use case first. Can we also get an example of output? It seems to me that the current output won't be valid json?

2021-04-08 11:31 UTC, stepanstipl commented
> Tools like Prowler and c7n already support jsonl. In Prowler's case it's the default for json output and in c7n, it's how it then puts things into SQS for notification. Far from arbitrary, it makes for easier importing into a data warehouse or documents in ElasticSearch. It's also the format that SecurityHub uses.

I'm not well familiar with these tools, and not sure about the use case - how would you use this `kubent` with Prowler? If the use case is putting `kubent` output into SQS, can you expand on that? 

Re. _AWS SecurityHub_ - it seems to require what is called _[AWS Security Finding Format (ASFF)](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format-syntax.html)_ format. Is the use case actually importing into AWS SecurityHub? If so, can you share any links to help me understand how SH requires single-lines json and how this would be integrated together?

I've found some info about [JSON lines](https://jsonlines.org/). As I understand it this format is intended for a stream, one record at a time, processing. I'm not sure it's a fit, as that is not something supported by `kubent`.

If the use case is running from a command line, perhaps the easy way is to use smth like _jq_ - you can easily run the following to convert:
```bash
$ kubent -o json | jq -c '.[]'
```

If the above doesn't work, can you elaborate a bit on the specific use case? You mentioned a couple of tools, but I'm still not very clear on how is this intended to be used.


> -q is also something both tools have - for the same reason. At the very least, it would be good to be able to adjust the log level properly - which is probably nicer?

Yep, I don't think the `-q` is the way to go here - it doesn't really silence _stdout,_ nor _stderr_ - just changes log level in the current implementation. On the other hand, adding an option to adjust the log level sounds like a good idea 👍.  This brings me back to understanding the use case... would custom log level work for you? For example simple mapping to zerolog's [levels](https://github.com/rs/zerolog#leveled-logging)?

> Not sure we need to split this up.

It seems like these features are orthogonal. It's easier to review, discuss and move forward smaller chunks of work (Not to mention how release notes are generated and split to at least separate commits will be required).

2021-06-17 11:59 UTC, stepanstipl commented
Configurable log level has been implemented in #127, in particular with `disabled` option to cover this use case. Thans for the suggestion 👍 .

As to JSON lines output format - I haven't heard more about the use case, but as for the command line use the simple way is to use `jq` (`kubent -o json | jq -c '.[]'`) to achieve the same, and gives the user the additional flexibility to transform to any format they're after. Additionally, as we don't support streaming, there doesn't seem to be any benefit in implementing this format inside this tool, and currently, there's no plan to do so.

2021-06-17 11:59 UTC, closed without merging