Fix: Add HPA to deprecated rego 1.25
doitintl/kube-no-trouble pull request #368
Opened 2022-09-26 18:37 UTC by stgrace

2022-09-28 12:01 UTC, stepanstipl requested changes
Many thanks @stgrace 👍 . In general, it looks good to me, just the note about code org. as this looks like it belongs in `1.26`. Other than that, the CI currently fails on some minor formatting issues, please see [^1], [^2].

Also, as to commit messages, I would suggest using the `feat: ` prefix, as this PR adds new functionality.

_Note: dupe of #330, related to #356_

[^1]: https://github.com/doitintl/kube-no-trouble/actions/runs/3130260911/jobs/5107405014
[^2]: https://github.com/doitintl/kube-no-trouble/actions/runs/3130260911/jobs/5107405540

2022-09-28 12:01 UTC, stepanstipl commented on pkg/rules/rego/deprecated-1-25.rego
> +			"since": "1.23",
Also, looks like there was `autoscaling/v2beta2`, might be worth adding it too + a test.

2022-09-30 15:07 UTC, dark0dave commented on pkg/rules/rego/deprecated-1-25.rego
> +			"since": "1.23",
I can add
its depricated in 25 too?

2022-10-01 18:09 UTC, stgrace commented on pkg/rules/rego/deprecated-1-25.rego
> +			"since": "1.23",
Alright,
So according to the docs it is actually deprecated in 1.25 (atleast autoscaling/v2beta1 is)
I can add autoscaling/v2beta2 to a new deprecated file already :)

2022-10-03 08:56 UTC, stepanstipl commented on pkg/rules/rego/deprecated-1-25.rego
> +			"since": "1.23",
> So according to the docs it is actually deprecated in 1.25 (atleast autoscaling/v2beta1 is)
> I can add autoscaling/v2beta2 to a new deprecated file already :)

Ah, sorry, I missed that, thanks for pointing it out. Currently, it wouldn't work to have the same resource twice in two separate files (we're thinking about improving this). You can have multiple deprecated versions (`old`) within one resource definition.

2022-10-03 09:00 UTC, stepanstipl commented
Thanks a lot, @stgrace 👍 

I think both `v2beta1` and `v2beta2` autoscaling APIs have bow been covered via https://github.com/doitintl/kube-no-trouble/pull/368, please correct me if that's not correct or missing anything there.

_(We had like 3 different PRs for this, should have all been closed when #368 was merged, I'm closing them now)_

2022-10-03 09:00 UTC, closed without merging