Added deprecations for kubernetes 1.26, 1.27, 1.29
doitintl/kube-no-trouble pull request #472
Opened 2023-04-04 07:24 UTC by ankursgupta87

- Added `FlowControlResources` deprecations for kubernetes [1.26](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#flowcontrol-resources-v126)
- Added deprecations for kubernetes [1.27](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27)
- Added deprecations for kubernetes [1.29](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-29)

2023-04-04 07:26 UTC, ankursgupta87 commented
@stepanstipl Kindly review

2023-04-04 10:17 UTC, dark0dave commented
Thanks for the links to the k8s docs very helpful!

LGTM @stepanstipl?

2023-04-04 10:30 UTC, dark0dave commented
Closes https://github.com/doitintl/kube-no-trouble/issues/470

2023-04-25 10:57 UTC, stepanstipl requested changes
Hi @ankursgupta87,

first thank you for the contribution 👍. From a quick look, I see a couple of issues before we can merge this:

- All new resource types need to be also added into the cluster collector [^1]
- Missing tests - any newly added resources need to be covered with tests, have a look at [^2] as an example
- Tests are failing on commit message, please see [^3] (you can also run tests locally - `make test`)

Hope it helps 🎉 

[^1]: https://github.com/doitintl/kube-no-trouble/blob/3f69b06e07c1388f880c8209c494d5aed600d062/pkg/collector/cluster.go#L71-L108
[^2]: https://github.com/doitintl/kube-no-trouble/blob/master/test/rules_125_test.go
[^3]: https://github.com/doitintl/kube-no-trouble#commit-messages

2023-07-03 09:53 UTC, david-ortiz-saez commented
hi @ankursgupta87 I see this is stuck for 60 days. Are you still interested in contributing? Should I try to do it? Thanks!

2023-08-29 04:19 UTC, matiasgarciaisaia commented
This PR has been superseeded by #504 - should be OK to be closed.

2023-08-29 08:21 UTC, closed without merging