fix: Properly represent multiple versions of the same custom resource
doitintl/kube-no-trouble pull request #516
Opened 2023-08-14 21:47 UTC by atzawada

I took a quick peek into the issue #515 that I opened earlier. Looks like it was an issue with how the Rego template was being rendered for additional custom resources. Simply combined the resource versions in the go code before passing it all off to the template.

If this approach is deemed ok, I will go back and write up some additional testing around this.

2023-08-16 21:23 UTC, dark0dave commented
This approach looks good to me please add tests.

2023-09-09 02:44 UTC, dark0dave commented
@atzawada you'll need to rebase this plus sign the commit.

2023-09-09 02:44 UTC, dark0dave requested changes
Tests, rebase and signed commit please.

2023-12-22 18:44 UTC, dark0dave approved these changes

2023-12-22 18:46 UTC, dark0dave commented
Looks like you'll need to format this.

2024-03-23 01:45 UTC, closed without merging

2024-06-13 15:40 UTC, w21froster commented
@atzawada this is some functionality I need so I am running your fork -- are you by chance able to get this formatted so it can be merged? 🙏